import numpy as np
import matplotlib.pyplot as plt
import cv2

a=cv2.imread('computer.jpg',0)
b=cv2.imread('mouse.jpeg',0)
c=np.add(a,b)
plt.subplot(1,3,1)
plt.imshow(a, cmap='gray')
plt.subplot(1,3,2)
plt.imshow(b, cmap='gray')
plt.subplot(1,3,3)
plt.imshow(c, cmap='gray')

d= cv2.imread('Fig0228(a)(angiography_mask_image).tif')
e= cv2.imread('Fig0228(b)(angiography_live_ image).tif')
f=np.subtract(d,e)
plt.subplot(1,3,1)
plt.imshow(d, cmap='gray')
plt.subplot(1,3,2)
plt.imshow(e, cmap='gray')
plt.subplot(1,3,3)
plt.imshow(f, cmap='gray')

g=cv2.imread('lena.png',0)
h=cv2.imread('img5.png',0)/255
i=np.multiply(g,h)
plt.subplot(1,3,1)
plt.imshow(g, cmap='gray')
plt.subplot(1,3,2)
plt.imshow(h, cmap='gray')
plt.subplot(1,3,3)
plt.imshow(i, cmap='gray')

img1 = cv2.imread("drawing_1.png")
img2 = cv2.imread("drawing_2.png")
bit_and = cv2.bitwise_and(img2, img1)
bit_or = cv2.bitwise_or(img2, img1)
bit_xor = cv2.bitwise_xor(img1, img2)
bit_not = cv2.bitwise_not(img1)
bit_not2 = cv2.bitwise_not(img2)
plt.subplot(2,3,1)
plt.imshow(img1, cmap='gray')
plt.title('Image 1')
plt.subplot(2,3,2)
plt.imshow(img2, cmap='gray')
plt.title('Image 2')
plt.subplot(2,3,3)
plt.imshow(bit_and, cmap='gray')
plt.title('Bitwise AND')
plt.subplot(2,3,4)
plt.imshow(bit_or, cmap='gray')
plt.title('Bitwise OR')
plt.subplot(2,3,5)
plt.imshow(bit_xor, cmap='gray')
plt.title('Bitwise XOR')
plt.subplot(2,3,6)
plt.imshow(bit_not2, cmap='gray')
plt.title('Bitwise NOT')
plt.subplots_adjust(hspace=0.25, wspace=0.35)

img1 = cv2.imread("drawing_1.png",0)
img2 = cv2.imread("drawing_2.png",0)
i0 = np.int32(np.array(np.zeros([250,500])))
c1 = np.int32(np.array(np.zeros([250,500])))
c2 = np.int32(np.array(np.zeros([250,500])))
c3 = np.int32(np.array(np.zeros([250,500])))
c4 = np.int32(np.array(np.zeros([250,500])))
b1 = np.int32(np.array(np.zeros([250,500])))
b2 = np.int32(np.array(np.zeros([250,500])))
for i in range(250):
    for j in range(500):
        b1[i][j] = np.binary_repr(img1[i][j])
        b2[i][j] = np.binary_repr(img2[i][j])
        
for i in range(250):
    for j in range(500):
        c1[i][j] = (b1[i][j] and b2[i][j])
        c2[i][j] = (b1[i][j] or b2[i][j])
        c3[i][j] = (b1[i][j] ^ b2[i][j])
        c4[i][j] = not(b1[i][j])

plt.subplot(2,3,1)
plt.imshow(img1, cmap='gray')
plt.title('Image 1')
plt.subplot(2,3,2)
plt.imshow(img2, cmap='gray')
plt.title('Image 2')
plt.subplot(2,3,3)
plt.imshow(c1, cmap='gray')
plt.title('Bitwise AND')
plt.subplot(2,3,4)
plt.imshow(c2, cmap='gray')
plt.title('Bitwise OR')
plt.subplot(2,3,5)
plt.imshow(c3, cmap='gray')
plt.title('Bitwise XOR')
plt.subplot(2,3,6)
plt.imshow(c4, cmap='gray')
plt.title('Bitwise NOT')
plt.subplots_adjust(hspace=0.25, wspace=0.35)